### ISSUE TITLE
new format: what when where

### ISSUE THREAD

**Issue by lionesstina** [robertvandeneynde/bots#9]
I am a girl, and I want what I want
which is ....the bot to learn what - where - when format ASAP!!!!
it is very urgent
if the bot doesn`t learn it anytime soon, I don`t know what I `ll do ....

**Comment by robertvandeneynde** [comment]
ok ~girl~, can you describe what you want ?

**Comment by lionesstina** [comment]
I will try, but no promises ....

**What** = Name

**When** = Date + Time (when it starts and when it finishes like 20 -23 for evening and 8-11 for morning. I think the end time of event is also important OR just the beginning of the event -  both options should exist

**Where** = Location (currently just "@") - if the event doesn`t have a location yet, is it ok?

but I also want it to be flexible. if I change my mind, I want the bot to keep up with the changes soon enough ))))))))))

**Comment by robertvandeneynde** [comment]
This relates to issue #7 that implements a new way to add events via YAML format :)

**Comment by robertvandeneynde** [comment]
> but I also want it to be flexible. if I change my mind, I want the bot to keep up with the changes soon enough ))))))))))

About that, we need to think of a way to easily _edit_ an event, currently we delete and recreate :)

**Comment by lionesstina** [comment]
do we need a new issue???

**Comment by robertvandeneynde** [comment]
Basic implementation done done in 7afd115f490693937c4faf303ebb72ee84476ed4

**Comment by robertvandeneynde** [comment]
Basic implementation done done in 7afd115f490693937c4faf303ebb72ee84476ed4
